CREATE TABLE DISCARDED_PRODUCT
(PDNO DECIMAL PRIMARY KEY,
PDNAME VARCHAR(10),
PDSUBNAME VARCHAR(10),
FACTNO VARCHAR(5) REFERENCES FACTORY(FACTNO),
PDDATE DATE,
PDCOST DECIMAL,
PDPRICE DECIMAL,
PDAMOUNT DECIMAL,
DISCARDED_DATE DATE
);